name: flutter_asroo_shop_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO:: UI
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  badges: ^2.0.3
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  pay: ^1.0.11

  # TODO:: State Management
  get: ^4.6.5

  # TODO:: Local
  get_storage: ^2.0.3

  # TODO:: Remote
  http: ^0.13.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1

  # TODO:: Location
  geolocator: ^9.0.1
  geocoding: ^2.0.5

  super_flutter:
    git:
      url: https://github.com/abdullahAlwajih/Super-Flutter.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/